<a href="https://colab.research.google.com/github/margarytochka/cv_workshop/blob/main/sociophysicsDataHandler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3QEUS0 - Sociophysics 1
## This Colab will explain how to install the SociophysicsDataHandler package

### Contacts:
*   A.Corbetta - a.corbetta@tue.nl
*   C.Pouw     - c.a.s.pouw@tue.nl
*   A.Gabbana  - a.gabbana@tue.nl

#### First, we need to install the API for accessing the data
Note: If you work in colab you need to perform the installation everytime you start the notebook; if you work offline (jupyter notebook/lab) you need to do this just once

In [1]:
!pip install -q sociophysicsDataHandler

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Building wheel for sociophysicsDataHandler (setup.py) ... done
  Building wheel for pyocclient (setup.py) ... done

Import the package

In [2]:
from sociophysicsDataHandler import SociophysicsDataHandler

Try to create a datahandler object.

In [3]:
dh = SociophysicsDataHandler()

ERROR. Fill the file 'auth.txt'
An empty one has been created for you
Content: (2 lines)
<access email>
<access token>

##### We get an error because we need to provide some credentials first.

1. An empty credentials file is created for you. It is called 'auth.txt'.
2. In colab, go to the left panel 'files'. You can change the content by double clicking on it.
3. Paste the acces credentials in the file and SAVE the file. (note, from time to me we change the credentials)

In [ ]:
# If you have done things correctly, this command should return you your own credentials
!cat auth.txt

Note: If you work in colab you need to create the `auth.txt` file everytime; if you work offline (jupyter notebook/lab) you need to do this just once.

### With the right credentials we can create the datahandler object.

In [ ]:
dh = SociophysicsDataHandler()

We can use the datahandler object to read the data that is provided to you in this course. However, to understand how and which data you can read it is convenient to first list the folders available on the storage.

The ouput of the cell below shows which files and folders area available to you.
 - All the data for the social media/ stocks case can be found in the 'econophysics' folder.
 - The trajectory data for the crowdflow case is separated based on where it is recorded: ehv -> Eindhoven, asdz -> Amsterdam Zuid, and ut -> Utrecht.

In [ ]:
folder_path = ''
dh.list_files(folder_path)

targeting path /storage/surfsara/ProRail_USE_LL_data/
Files listed. Accessible as <this-object>.filelist

,path,name,attributes
0,/storage/surfsara/ProRail_USE_LL_data/asdz/,asdz,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."
1,/storage/surfsara/ProRail_USE_LL_data/config/,config,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."
2,/storage/surfsara/ProRail_USE_LL_data/econophy...,econophysics,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."
3,/storage/surfsara/ProRail_USE_LL_data/ehv/,ehv,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 17..."
4,/storage/surfsara/ProRail_USE_LL_data/sync.sh,sync.sh,"{'{DAV:}getlastmodified': 'Wed, 02 Mar 2022 18..."
5,/storage/surfsara/ProRail_USE_LL_data/upload_l...,upload_log.csv,"{'{DAV:}getlastmodified': 'Wed, 13 Oct 2021 10..."
6,/storage/surfsara/ProRail_USE_LL_data/ut/,ut,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."

#### Example ProRail data

The cell below lists  all the files recorded in Eindhoven for a specific day.

In [ ]:
folder_path = 'ehv/platform2.1/20230428/'
dh.list_files(folder_path)

targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20230428/
Files listed. Accessible as <this-object>.filelist

,path,name,attributes
0,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042800_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
1,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042801_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
2,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042802_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
3,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042803_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
4,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042804_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
5,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042805_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
6,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042806_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
7,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042807_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
8,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042808_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
9,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042809_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
10,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042810_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
11,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042811_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
12,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042812_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
13,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042813_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
14,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042814_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
15,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042815_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
16,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042816_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
17,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042817_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
18,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042818_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
19,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042819_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
20,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042820_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
21,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042821_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
22,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042822_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."
23,/storage/surfsara/ProRail_USE_LL_data/ehv/plat...,EHV_Platform2.1_2023042823_trajectorie.parquet,"{'{DAV:}getlastmodified': 'Mon, 11 Sep 2023 14..."

We can use the datahandler to read one of the files.

In [ ]:
file_target = "EHV_Platform2.1_2023042819_trajectorie.parquet"
file_path = folder_path + file_target
dh.fetch_prorail_data_from_path(file_path) # Read the data
dh.df.head() # Display first 5 rows

trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20230428/EHV_Platform2.1_2023042819_trajectorie.parquet
data fetched. Accessible as <this-object>.df

,date_time_utc,tracked_object,x_pos,y_pos,datetime
0,1.682701e+12,13876369,-3439.0,61644.0,2023-04-28 19:00:00+02:00
1,1.682701e+12,13877889,-2539.0,63361.0,2023-04-28 19:00:00+02:00
2,1.682701e+12,13877975,646.0,50268.0,2023-04-28 19:00:00+02:00
3,1.682701e+12,13877976,-3952.0,9838.0,2023-04-28 19:00:00+02:00
4,1.682701e+12,13876369,-3436.0,61644.0,2023-04-28 19:00:00.100000+02:00

For more advanced usage, please refer to the notebook `trajectory_analysis.ipynb`.

#### Example Druyfkens data

We can do a similar thing for the stockprice data provide by Druyfkens.

In [ ]:
folder_path = 'econophysics/prices'
dh.list_files(folder_path)

targeting path /storage/surfsara/ProRail_USE_LL_data/econophysics/prices
Files listed. Accessible as <this-object>.filelist

,path,name,attributes
0,/storage/surfsara/ProRail_USE_LL_data/econophy...,daily_close_prices.csv,"{'{DAV:}getlastmodified': 'Fri, 16 Jul 2021 08..."
1,/storage/surfsara/ProRail_USE_LL_data/econophy...,daily_open_prices.csv,"{'{DAV:}getlastmodified': 'Fri, 16 Jul 2021 08..."
2,/storage/surfsara/ProRail_USE_LL_data/econophy...,hourly_prices.csv,"{'{DAV:}getlastmodified': 'Fri, 16 Jul 2021 08..."

In [ ]:
dh.fetch_econophysics_data_from_path("econophysics/prices/daily_open_prices.csv") # Read the data
dh.df.head() # Display first 5 rows

trying to fetch: /storage/surfsara/ProRail_USE_LL_data/econophysics/prices/daily_open_prices.csv
data fetched. Accessible as <this-object>.df

             BBBY  NOKIA   AMC       VIAC       FIZZ   GME        AAPL    LGND
2020-09-01  12.06  4.106  5.79  26.999016  37.947065  7.27  132.258470  101.75
2020-09-02  13.13  3.968  7.00  26.989247  39.243438  7.78  136.905577  101.73
2020-09-03  12.39  4.035  6.95  27.731623  38.999194  7.90  126.347588  102.58
2020-09-04  12.04  3.810  6.73  27.751159  38.773738  7.78  119.411755   98.73
2020-09-07    NaN  3.726   NaN        NaN        NaN   NaN         NaN     NaN

For more advance usage we refer to the notebooks in this repo https://github.com/ValerioGemm/socioPhysicsTUe_econ.